### ISSUE TITLE
Liability statement (liablityStatement) wrong key value written to mdJSON

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdEditor#497]
The mdEditor incorrectly writes the "[liabilityStatement](https://mdtools.adiwg.org/#viewer-page?v=2-3-0-1)" to mdJSON as "liablityStatement" (missing "i"). The translator correctly imports from CSDGM and writes to JSON as ```liabilityStatement```.

Records imported from CSDGM may contain a correctly named key, which will not be displayed in the editor. Subsequent editing of the record could result in the presence of two statements, one with the correcly spelled key and another with the incorrectly spelled key.

# Tasks:
  - [x] Rename key in mdEditor to liabilityStatement
  - [x] Determine how to fix existing data. (perform on import and export) 
  - [x] Case 1: no liability statement present; no action needed.
  - [x] Case 2: single liability statement using **correct** spelling; no action needed.
  - [x] Case 3: single liability statement using **incorrect** spelling; rename key or copy and delete.
  - [ ] Case 4: two liability statements present using **both** correct and incorrect keys. The value of the misspelled key (entered via the editor) shall replace the value of the correctly spelled key (imported from CSDGM). The misspelled key shall then be deleted from the JSON.
 
## See:
I see the issue, it looks like there a misspelling, liablityStatement vs liabilityStatement (missing i)

this is coming from mdEditor
https://github.com/adiwg/mdEditor/blob/f94770686df07ef76aa111f8f9734b32bbad7f21/app/pods/components/object/md-distribution/template.hbs#L22

since this is in the Production version I'll do a little digging on how we can handle upgrading existing mdJson to the correct spelling transparently in the editor, and I suppose we should handle both spellings in the translator

_Originally posted by @timothypage in https://github.com/adiwg/mdTranslator/issues/236#issuecomment-1287069856_

**Comment by hmaier-fws** [comment]
@jwaspin before this can be merged in, the logic to handle use cases 3 and 4 needs to be added otherwise users may experience data loss.

**Comment by jwaspin** [comment]
https://github.com/adiwg/mdTranslator/issues/236 is related
